add_subdirectory(csp)
add_subdirectory(singleton)
add_subdirectory(condition_variable)
add_subdirectory(async)
add_subdirectory(thread_pool)
add_subdirectory(joining_thread)
add_subdirectory(memory_order)
add_subdirectory(reordering)
add_subdirectory(quick_sort)
if(UNIX)
  add_subdirectory(mutex_lock)
endif()
